### ISSUE TITLE
Vite v5 says "The CJS build of Vite's Node API is deprecated."

### ISSUE THREAD

**Issue by darkvertex** [mathe42/vite-plugin-comlink#117]
Running a project with Vite v5.0.10 and vite-plugin-comlink, I get:

```
$ VITE_CJS_TRACE=true pnpm run dev

> <redacted>@1.0.0 dev /<redacted>/repos/<redacted>
> vite

Trace: The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
    at warnCjsUsage (/<redacted>/node_modules/.pnpm/vite@5.0.10/node_modules/vite/index.cjs:32:3)
    at Object.<anonymous> (/<redacted>/node_modules/.pnpm/vite@5.0.10/node_modules/vite/index.cjs:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/<redacted>/node_modules/.pnpm/vite-plugin-comlink@3.0.5_comlink@4.4.1_vite@5.0.10/node_modules/vite-plugin-comlink/dist/index.js:31:19)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
```

https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated

**Comment by mathe42** [comment]
fixed with 4.0
