### ISSUE TITLE
can't set worker option with name variable

### ISSUE THREAD

**Issue by CSNight** [mathe42/vite-plugin-comlink#64]
"vite-plugin-comlink": "^3.0.2",
`
  const workerId = nanoid()

  console.log(workerId)

  const workerOpt = {
    name: workerId
  }

  return new ComlinkWorker<typeof import('./imgInp.worker')>(new URL("./imgInp.worker.ts", import.meta.url), workerOpt);
`
when set workerOption like this, will cause this  compile error down below
`
 [vite] Internal server error: JSON5: invalid character 'w' at 1:1
  Plugin: comlink
  at syntaxError (E:\WebStorm_JS_Workspace\storm-portal-next\node_modules\vite-plugin-comlink\dist\index.js:861:15)
      at invalidChar (E:\WebStorm_JS_Workspace\storm-portal-next\node_modules\vite-plugin-comlink\dist\index.js:824:10)
      at literal (E:\WebStorm_JS_Workspace\storm-portal-next\node_modules\vite-plugin-comlink\dist\index.js:601:13)
      at Object.value (E:\WebStorm_JS_Workspace\storm-portal-next\node_modules\vite-plugin-comlink\dist\index.js:223:9)
      at lex (E:\WebStorm_JS_Workspace\storm-portal-next\node_modules\vite-plugin-comlink\dist\index.js:107:39)
      at Object.parse2 [as parse] (E:\WebStorm_JS_Workspace\storm-portal-next\node_modules\vite-plugin-comlink\dist\index.js:73:13)
      at workerReplacer (E:\WebStorm_JS_Workspace\storm-portal-next\node_modules\vite-plugin-comlink\dist\index.js:2063:38)
      at String.replace (<anonymous>)
      at TransformContext.transform (E:\WebStorm_JS_Workspace\storm-portal-next\node_modules\vite-plugin-comlink\dist\index.js:2081:14)
      at Object.transform (E:\WebStorm_JS_Workspace\storm-portal-next\node_modules\vite\dist\node\chunks\dep-e1fc1d62.js:38961:53)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async doTransform (E:\WebStorm_JS_Workspace\storm-portal-next\node_modules\vite\dist\node\chunks\dep-e1fc1d62.js:55918:29)
`

**Comment by mathe42** [comment]
This is expected! The workeroptions have to be Static! So a simple JS object. This is a Vite limitation that also expands to here.

**Comment by CSNight** [comment]
ok  thanks !  Is there any way to solve this problems?

**Comment by mathe42** [comment]
I looked again into the vite code it is here:
https://github.com/vitejs/vite/blob/main/packages/vite/src/node/plugins/workerImportMetaUrl.ts#L54

I think it could be changed so that only the type field has to be static but thats not that simple.

vite-plugin-comlink uses the same method to get the options https://github.com/mathe42/vite-plugin-comlink/blob/main/src/index.ts#L100

There we also set the type in development to `module` and check for the custom `replacement` field. 

Both could be done by parsing this part into an AST and modify it - so more cases that are allowed. For me to chnage it first vite has to be changed. And then I will implement it here (when I have time).

I currently don't have time for any of that but feel free to try it yourself!

And I'm not sure for what do you actually need the `name` field? I can't think about a use case where you need it...

**Comment by CSNight** [comment]
thanks a lot, i will try it myself. 
The purpose to do this is help to debug and find the specified worker when more same workers are load to run by different context

**Comment by mathe42** [comment]
Will close this for now!
