### ISSUE TITLE
"SyntaxError: Cannot use import statement outside a module" when using the plugin

### ISSUE THREAD

**Issue by peter50216** [mathe42/vite-plugin-comlink#8]
As title, looks like for some reason vite is using CommonJS modules for me.

```
failed to load config from <project>/vite.config.ts
error when starting dev server:
<project>/node_modules/.pnpm/vite-plugin-comlink@1.1.0_comlink@4.3.1+vite@2.5.10/node_modules/vite-plugin-comlink/dist/index.js:1
import { readFileSync, writeFileSync, existsSync } from "fs";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:988:16)
    at Module._compile (internal/modules/cjs/loader.js:1036:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (<project>/vite.config.ts:35:45)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.require.extensions.<computed> [as .ts] (<project>/node_modules/.pnpm/vite@2.5.10/node_modules/vite/dist/node/chunks/dep-36bf480c.js:77283:20)
 ELIFECYCLE  Command failed with exit code 1.
```

A quick fix is to change `tsconfig.json` to `"module": "commonjs"`.

It might be helpful to build both cjs and esm for the npm package (similar to other vite plugins: https://github.com/antfu/vite-plugin-pwa/blob/main/scripts/commands.ts#L2).

**Comment by peter50216** [comment]
Obsolete with 2.0.0-beta.1
